chat/urls.py
from django.urls import path, include
from . import views
from django.urls import re_path

app_name = "chat"

urlpatterns = [
    path("dashboard", views.index, name="dashboard"),
    path("addfriend/<str:name>", views.addFriend, name="addFriend"),
    path("delete_friend", views.deleteFriend, name="deleteFriend"),
    path("chat/<str:username>", views.chat, name="chat"),
    path("request", views.FriendRequest, name="FriendRequest"),
    path('waiting-room', views.waiting_room, name="waiting-room"),
    path('api/room', views.room, name='room'),

]

chat/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):

    id = models.AutoField(primary_key=True, unique=True, editable=False, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=None, null=True, blank=True)
    name = models.CharField(max_length=25)
    username = models.CharField(max_length=20, unique=True)
    online = models.IntegerField(default=0)
    online_for = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f"{self.username}"


class Friends(models.Model):

    id = models.AutoField(primary_key=True, unique=True, editable=False, blank=True)
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    friend = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name="friend")
    note = models.CharField(max_length=100, blank=True, default="")
    accepted = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user} - {self.friend}"


#Store E2EE keys
class Keys(models.Model):
    id = models.AutoField(primary_key=True, unique=True, editable=False, blank=True)
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    public_key = models.TextField()

    def __str__(self):
        return f"{self.user}"

chat/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import UserProfile, Friends
from django.views.decorators.csrf import csrf_exempt
from django.http.response import JsonResponse
from rest_framework.parsers import JSONParser
from channels.db import database_sync_to_async
from chat.models import Keys
import base64
import urllib
from registration.models import user_type
from chat.tools import getFriendsList, getUserId
from django.views.decorators.clickjacking import xframe_options_exempt
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist


def index(request):
    if not request.user.is_authenticated:
        return redirect("registration:home")

    username = request.user.username
    id = getUserId(username)
    friends = getFriendsList(id)
    if user_type.objects.get(user=request.user).type == "Anonymous":
        return render(request, "chat/Base.html", {'friends': friends, 'anonymous':True})

    return render(request, "chat/Base.html", {'friends': friends})


def addFriend(request, name):
    friend = name
    friend = UserProfile.objects.get(username=name)
    note = request.GET.get("note")
    if len(note) > 100:
        return HttpResponse("<script>alert('Note too long!'); window.location.href='/dashboard';</script>")

    if not UserProfile.objects.filter(username=friend).exists():
        return redirect("/dashboard")

    if Friends.objects.filter(user=UserProfile.objects.get(username=request.user.username), friend=friend).exists():
        return redirect("/dashboard")

    User_Adding_Friend = Friends(user=UserProfile.objects.get(username=request.user.username), friend=friend, accepted=True)
    User_Adding_Friend.save()

    Friend_Adding_User = Friends(user=friend, friend=UserProfile.objects.get(username=request.user.username),note=note, accepted=False)
    Friend_Adding_User.save()

    return redirect("/dashboard")

@xframe_options_exempt
def chat(request, username):
    try:
        friend = UserProfile.objects.get(username=username)
    except UserProfile.DoesNotExist:
        return redirect("chat:dashboard")
    id = getUserId(request.user.username)
    curr_user = UserProfile.objects.get(id=id)

    #messages = Messages.objects.filter(sender_name=id, receiver_name=friend.id) | Messages.objects.filter(sender_name=friend.id, receiver_name=id)
    public_key = Keys.objects.get(user=friend).public_key
    #base64 encoded
    public_key = base64.b64encode(public_key.encode('utf-8')).decode('utf-8')
    public_key = urllib.parse.quote_plus(public_key)
    friends = getFriendsList(id)
    if user_type.objects.get(user=request.user).type == "Anonymous":
        
        response = render(request, "chat/messages.html",
                        {
                         'curr_user': curr_user, 'friends': friends, 'friend':friend, 'anonymous':True})
        response.set_cookie('public_key', public_key)
        return response
    if request.method == "GET":
        response = render(request, "chat/messages.html",
                      {
                       'friends': friends,
                       'curr_user': curr_user, 'friend': friend})
        response.set_cookie('public_key', public_key)
        return response

@xframe_options_exempt
def waiting_room(request):

    if not request.user.is_authenticated:
        return redirect('/')
    try:

        if request.method == 'GET':
            user = request.GET.get('user')
            curr_user = UserProfile.objects.get(username=request.user.username)
            friend = UserProfile.objects.get(username=user)

            if Friends.objects.filter(user=curr_user.id, friend=friend).exists():
                if Friends.objects.get(user=curr_user.id, friend=friend).accepted == False:
                    #redirect with get parameter
                    return redirect(f"/request?user={user}")
            
            if Friends.objects.filter(user=friend, friend=curr_user.id).exists():
                if Friends.objects.get(user=friend, friend=curr_user.id).accepted == False:
                    return HttpResponse("<script>alert('You cannot chat with this user until, they accept your friend request!'); window.location.href='/';</script>")

            if not Friends.objects.filter(user=curr_user.id, friend=friend).exists() or not Friends.objects.filter(user=friend, friend=curr_user.id).exists():
                return HttpResponse("<script>alert('You cannot chat with this user until, they add you as a friend!'); window.location.href='/';</script>")

        username = request.user.username
        id = getUserId(username)
        friends = getFriendsList(id)

        return render(request, "chat/waiting_room.html", {"friend": friend.name, 'friends': friends})
    except:
        return HttpResponse("<script>alert('something went wrong'); window.location.href='/';</script>")
    
@xframe_options_exempt
def room(request):
    if request.method == "GET":
        ForUser = request.GET.get("user")
        try:
            if UserProfile.objects.get(username=str(ForUser)).online==1 and UserProfile.objects.get(username=str(ForUser)).online_for==UserProfile.objects.get(username=request.user.username):
                return JsonResponse({"status": True})
            else:
                return JsonResponse({"status": False})
        except Exception as e:
            pass
        return JsonResponse({"status": False})
    return JsonResponse({"status": False})

def FriendRequest(request):
    if not request.user.is_authenticated:
        return redirect('registration:login')
    
    if request.method == "GET":
        if not request.GET.get("user"):
            return redirect("chat:dashboard")
    
        friend = request.GET.get("user")
        try:
            if Friends.objects.filter(user=UserProfile.objects.get(user=request.user), friend=UserProfile.objects.get(user=User.objects.get(username=friend))).exists():
                note = Friends.objects.get(user=UserProfile.objects.get(user=request.user), friend=UserProfile.objects.get(user=User.objects.get(username=friend))).note

                username = request.user.username
                id = getUserId(username)
                friends = getFriendsList(id)

                return render(request, "chat/FriendRequest.html", {"RequestFrom": friend, "note": note, 'friends': friends})
        except ObjectDoesNotExist:
            return redirect("chat:dashboard")
        
    if request.method == "POST":
        request_from = request.POST.get("request_from")
        #validations
        if Friends.objects.filter(user=UserProfile.objects.get(user=request.user), friend=UserProfile.objects.get(user=User.objects.get(username=request_from))).exists():
            action = request.POST.get("action")
            if action == "accept":
                friend = UserProfile.objects.get(user=User.objects.get(username=request_from))
                Friends.objects.filter(user=UserProfile.objects.get(user=request.user), friend=friend).update(accepted=True)
                Friends.objects.filter(user=friend, friend=UserProfile.objects.get(user=request.user)).update(accepted=True)
                return redirect("chat:dashboard")
            elif action == "reject":
                friend = UserProfile.objects.get(user=User.objects.get(username=request_from))
                Friends.objects.filter(user=UserProfile.objects.get(user=request.user), friend=friend).delete()
                Friends.objects.filter(user=friend, friend=UserProfile.objects.get(user=request.user)).delete()
                return redirect("chat:dashboard")

    return render(request, "chat/FriendRequest.html")

def deleteFriend(request):
    if not request.user.is_authenticated:
        return redirect("registration:login")
    
    if request.method == "GET":
        friend = request.GET.get("friend")
        try:
            if Friends.objects.filter(user=UserProfile.objects.get(user=request.user), friend=UserProfile.objects.get(user=User.objects.get(username=friend))).exists():
                friend = UserProfile.objects.get(user=User.objects.get(username=friend))
                Friends.objects.filter(user=UserProfile.objects.get(user=request.user), friend=friend).delete()
                Friends.objects.filter(user=friend, friend=UserProfile.objects.get(user=request.user)).delete()
                return JsonResponse({"status": True, "message": "Friend deleted successfully!"})
        except ObjectDoesNotExist:
            return redirect("chat:dashboard")
    return redirect("chat:dashboard")

chat/templates/chat/FriendRequest.html
{% extends "chat/Base.html" %}
{% load static %}

{% block content %}
<style>
    i.size {
       font-size: 100px;
    }
 </style>
<link rel="stylesheet" href="{% static 'css/chat/FriendRequest.css' %}">
<div class="text-center">
    <h1 id="request-text">You have received friend request from: <u>{{RequestFrom}}</u></h1>
    {% if note %}
    <h5>Request Note: <b>{{note}}</b></h5>
    {% endif %}
    <br>
    <button class="btn btn-outline-success request-button" id="accept-button"><i class="fa-solid fa-check"></i> </button>
    Accept

    &nbsp;&nbsp;&nbsp;

    <button class="btn btn-outline-danger request-button" id="reject-button"><i class="fa-solid fa-xmark"></i></button>
    Reject
</div>

<script>
    //Ajax request to accept or reject friend request
    document.getElementById("accept-button").addEventListener("click", function () {
        $.ajax({
            type: "POST",
            url: "{% url 'chat:FriendRequest' %}",
            data: {
                'csrfmiddlewaretoken': "{{ csrf_token }}",
                'request_from': "{{RequestFrom}}",
                'action': "accept"

            },
            success: function (data) {
                Swal.fire({
                title: "Friend request accepted!",
                confirmButtonColor: "#003d89",
                icon: "success"
                }).then(function(){
                    window.location.href = "{% url 'chat:dashboard' %}";
                })
            }
        });
    });

    document.getElementById("reject-button").addEventListener("click", function () {
        $.ajax({
            type: "POST",
            url: "{% url 'chat:FriendRequest' %}",
            data: {
                'csrfmiddlewaretoken': "{{ csrf_token }}",
                'request_from': "{{RequestFrom}}",
                'action': "reject"

            },
            success: function (data) {
                Swal.fire({
                title: "Friend request rejected!",
                confirmButtonColor: "#003d89",
                icon: "success"
                }).then(function(){
                    window.location.href = "{% url 'chat:dashboard' %}";
                });
            }
        });
    });

</script>

<script type="text/javascript" src="{% static 'js/chat/waiting_room.js' %}"></script>

{% endblock %}

chat/templates/chat/chats.html
{% extends "chat/Base.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/chat/chats.css' %}">

<div style="margin-top: 0px">
    <h3>{{friend.name}}</h3>
    <span id="live-notification-dot" class="logged-in">● </span><small id="live-notification-text">Connecting...</small>
</div>
<p class="text-center"><i class="fa-solid fa-lock"></i> Messages are End-to-End encrypted!</p>
<p onclick="trashmessages();"
    style="cursor: pointer; color:rgb(200, 57, 57); text-align: right; margin-bottom: 5vh;"> <i
        class="fa fa-trash-can fa-xl" aria-hidden="true" onclick="trashmessages();"></i> Trash Messages </p>
<p id="typing" style="color: green; font-size: 1em; margin-top: -10px;"></p>

<div class="messages" id="board">
    {% block message %}
    {% endblock %}
</div>
<div class="row">
    <form method="post" class="form-group" id="chat-box">
        {% csrf_token %}
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <input style="border-radius: 15px;" type="text" placeholder=" Enter your message" name="message"
                    id="msg_field" autocomplete="off"> &nbsp; &nbsp;
                    <label class="select" for="MessageDestroy">
                        <select id="MessageDestroy" required="required">
                          <option value="0" selected="selected">Do not destroy</option>
                          <option value="5">5 seconds</option>
                          <option value="10">10 seconds</option>
                          <option value="30">30 seconds</option>
                          <option value="60">1 minutes</option>
                          <option value="300">5 minutes</option>
                          <option value="600">10 minutes</option>
                          <option value="3600">1 hour</option>
                        </select>
                      </label>&nbsp; &nbsp;
                <button style="border-radius: 50%;" type="submit" name="send" class="btn btn-primary" id="send_btn"> <i
                        class="fa-solid fa-paper-plane"></i></button>

            </div>
        </div>
    </form>
</div>
<small id="note"></small>


<script>
    var messageBody = document.querySelector('.messages');
    messageBody.scrollTop = messageBody.scrollHeight - messageBody.clientHeight;

    sender_id = "{{ friend.id }}";
    receiver_id = "{{ curr_user.id }}";

    function scrolltoend() {
        $('#board').stop().animate({
            scrollTop: $('#board')[0].scrollHeight
        }, 800);
    }

    const text_box = '<div class="container darker">' +
        '<img src="{% static 'images/user_image.jpg' %}" alt="Avatar" class="right" style="width:100%;">' +
    '<p>{description}</p>' +
        '<span class="time-right">{time}</span>' +
        '</div>'
</script>

<script>
    var input = document.getElementById("msg_field");
    //allow only 190 words
    input.addEventListener("input", function () {
        if (this.value.length > 190)
            document.getElementById("note").innerHTML = "Only 190 characters are allowed!";

        this.value = this.value.slice(0, 190);
        //show note that only 190 characters are allowed
    });
    //remove note when user stops typing
    input.addEventListener("blur", function () {
        document.getElementById("note").innerHTML = "";
    });
</script>

<script src="{% static 'js/chat/chats.js' %}"></script>

{% endblock %}

chat/templates/chat/messages.html
{% extends 'chat/chats.html' %}
{% load static %}

<script>
    function scrolltoend() {
        $('#board').stop().animate({
            scrollTop: $('#board')[0].scrollHeight
        }, 800);
    }

    
</script>

chat/templates/chat/waiting_room.html
{% extends "chat/Base.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/chat/waiting_room.css' %}">
<div class="text-center">
    <h1 id="waiting_text">Waiting for <u>{{friend}}</u> to connect</h1>
</div>
<div id="loader-position">
    <span class="loader"></span>
</div>

<script>

    var text = document.getElementById("waiting_text");
    var dots = 0;
    var dots_interval = setInterval(function () {
        if (dots < 3) {
            text.innerHTML += ".";
            dots++;
        } else {
            text.innerHTML = "Waiting for <u>{{friend}}</u> to connect";
            dots = 0;
        }
    }, 500);
</script>

<script type="text/javascript" src="{% static 'js/chat/waiting_room.js' %}"></script>

{% endblock %}